# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Dump GitHub context
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '===================================='
          echo "$GITHUB_TOKEN"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          REPO_OWNER="primeap"
          REPO_NAME="poc-1"
          BRANCH_NAME="THIS-IS-GREAT-BRANCH-NAME"
          
          response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_NAME")
            
          echo "------------------------------->>>><<<<------------------------"  
          echo "$response"  
          
          if [[ "$response" == *"\"message\":\"Branch not found\""* ]]; then
            echo "Branch not found. Workflow terminated."
            exit 1
          else
            echo "Branch exists"
          fi
        
      - name: Clone Openapi repo
        continue-on-error: false
        uses: actions/checkout@v2
        with:
          path: openapi
          submodules: recursive
          repository: MHEducation/openapi
        uses: actions/checkout@v3
        with:
          path: poc-1
          submodules: recursive
          repository: primeap/poc-1
          ref: abcd
          
      - name: Clone Openapi repo *******
        run: echo Hello, world!?????????????????
      
